--관리자

SELECT * FROM DBA_TABLESPACES;
--사용자삭제
DROP USER iouser CASCADE;
--TABLESPACE삭제 
DROP TABLESPACE iolistDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

--시그마 생성
CREATE TABLESPACE IolistDB
DATAFILE  'C:/oraclexe/data/iolist.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

--유저생성
CREATE USER iouser IDENTIFIED BY iouser
DEFAULT TABLESPACE IolistDB;


--dba 권한줌
GRANT DBA TO iouser;


--오라클의 시스템값
SELECT * FROM DBA_PROFILES;

--오라클에 새로 등록된 사용자의 Password 만료일자
--기본값이 180으로 되어있어서
--새로운 사용자 등록후 비번을 변경하지 않으면 
--180일 이후에는 접속이 불가능해진다

SELECT * FROM DBA_PROFILES
WHERE RESOURCE_NAME = 'PASSWORD_LIFE_TIME';

ALTER PROFILE
DEFAULT LIMIT PASSWORD_LIFE_TIME
UNLIMITED;

